-- Ensure we are operating inside the default PDB and in the application user's schema
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = myuser;

-- Create table distros
CREATE TABLE distros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    release_year NUMBER(4) NOT NULL
);

-- Create table packages
CREATE TABLE packages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    version VARCHAR2(50) NOT NULL,
    distro_id NUMBER REFERENCES distros(id)
);

-- Insert distros (22)
INSERT INTO distros (name, release_year) VALUES ('Ubuntu', 2004);
INSERT INTO distros (name, release_year) VALUES ('Fedora', 2003);
INSERT INTO distros (name, release_year) VALUES ('Debian', 1993);
INSERT INTO distros (name, release_year) VALUES ('Arch Linux', 2002);
INSERT INTO distros (name, release_year) VALUES ('openSUSE', 2005);
INSERT INTO distros (name, release_year) VALUES ('CentOS', 2004);
INSERT INTO distros (name, release_year) VALUES ('Red Hat Enterprise Linux', 2000);
INSERT INTO distros (name, release_year) VALUES ('Linux Mint', 2006);
INSERT INTO distros (name, release_year) VALUES ('Manjaro', 2011);
INSERT INTO distros (name, release_year) VALUES ('Kali Linux', 2013);
INSERT INTO distros (name, release_year) VALUES ('Slackware', 1993);
INSERT INTO distros (name, release_year) VALUES ('Gentoo', 2000);
INSERT INTO distros (name, release_year) VALUES ('Elementary OS', 2011);
INSERT INTO distros (name, release_year) VALUES ('Pop!_OS', 2017);
INSERT INTO distros (name, release_year) VALUES ('Zorin OS', 2009);
INSERT INTO distros (name, release_year) VALUES ('Solus', 2015);
INSERT INTO distros (name, release_year) VALUES ('MX Linux', 2014);
INSERT INTO distros (name, release_year) VALUES ('Parrot OS', 2013);
INSERT INTO distros (name, release_year) VALUES ('Alpine Linux', 2005);
INSERT INTO distros (name, release_year) VALUES ('Peppermint OS', 2010);
INSERT INTO distros (name, release_year) VALUES ('Clear Linux', 2015);
INSERT INTO distros (name, release_year) VALUES ('EndeavourOS', 2019);

-- Insert packages (mirrors your list up to the last complete entry)
INSERT INTO packages (name, version, distro_id) VALUES ('bash', '5.1', 1);
INSERT INTO packages (name, version, distro_id) VALUES ('coreutils', '8.32', 1);
INSERT INTO packages (name, version, distro_id) VALUES ('vim', '8.2', 1);
INSERT INTO packages (name, version, distro_id) VALUES ('nano', '6.2', 2);
INSERT INTO packages (name, version, distro_id) VALUES ('dnf', '4.8.0', 2);
INSERT INTO packages (name, version, distro_id) VALUES ('gcc', '10.2', 2);
INSERT INTO packages (name, version, distro_id) VALUES ('apt', '2.2.4', 3);
INSERT INTO packages (name, version, distro_id) VALUES ('dpkg', '1.20.9', 3);
INSERT INTO packages (name, version, distro_id) VALUES ('pacman', '6.0.2', 4);
INSERT INTO packages (name, version, distro_id) VALUES ('zypper', '1.14.52', 5);
INSERT INTO packages (name, version, distro_id) VALUES ('yum', '4.2.23', 6);
INSERT INTO packages (name, version, distro_id) VALUES ('rpm', '4.16.1', 7);
INSERT INTO packages (name, version, distro_id) VALUES ('synaptic', '0.90.2', 8);
INSERT INTO packages (name, version, distro_id) VALUES ('pamac', '10.5.5', 9);
INSERT INTO packages (name, version, distro_id) VALUES ('metasploit', '6.1.21', 10);
INSERT INTO packages (name, version, distro_id) VALUES ('slackpkg', '15.0.0', 11);
INSERT INTO packages (name, version, distro_id) VALUES ('portage', '3.0.18', 12);
INSERT INTO packages (name, version, distro_id) VALUES ('pantheon-files', '4.0.4', 13);
INSERT INTO packages (name, version, distro_id) VALUES ('pop-shell', '1.2.0', 14);
INSERT INTO packages (name, version, distro_id) VALUES ('zorin-connect', '1.0.0', 15);
INSERT INTO packages (name, version, distro_id) VALUES ('eopkg', '3.8.0', 16);
INSERT INTO packages (name, version, distro_id) VALUES ('mx-tools', '20.3', 17);
INSERT INTO packages (name, version, distro_id) VALUES ('parrot-tools', '4.11', 18);
INSERT INTO packages (name, version, distro_id) VALUES ('apk-tools', '2.12.7', 19);
INSERT INTO packages (name, version, distro_id) VALUES ('peppermint-setup', '10.0', 20);
INSERT INTO packages (name, version, distro_id) VALUES ('clr-installer', '2.0.47', 21);
INSERT INTO packages (name, version, distro_id) VALUES ('eos-welcome', '3.8.18', 22);
INSERT INTO packages (name, version, distro_id) VALUES ('htop', '3.2.2', 1);
INSERT INTO packages (name, version, distro_id) VALUES ('neofetch', '7.1.0', 2);

COMMIT;
